### ISSUE TITLE
Videos Pausing around 13-14 Minutes

### ISSUE THREAD

**Issue by Stack3r** [antonic901/xbox-youtube#6] opened 2022-09-06 02:56 UTC
Hello, I am having an issue where whatever video I watch if it’s decently long it will stop playing around the 13/14 minute mark. The app appears to still be working when this happens but I have to exit the current video and load up something else

**Comment by Stack3r** [comment] 2022-09-06 03:08
Here’s an example, it just got to the 13:08 mark, playback was fine and now it’s just stuck
![image](https://user-images.githubusercontent.com/18194679/188538776-710cd693-e3a1-4d63-b0cf-b30c8a6e35f8.jpg)

**Comment by antonic901** [comment] 2022-09-08 18:31
Hi. I currently don't have AV cable for my Xbox so I can't test it on real hardware. Hovever I've tried to replicate this bug on Xemu and for some reason, when reaching 12:48, memory usage was over 90% percent. Free memory was below 1MB and that's the reason why playback stopped. Sometimes whole Xbox will froze. There was also one guy from Facebook who had same problems.

I currently don't have time to take a closer look, but I hope this isn't some bug related to XBMC4Xbox. Because if it is, there is nothing I can do. I hope I'll be able to find a way on adaptive streams implementation. Adaptive streams will remove video length limitation and also could fix this memory issues. When I get time I will take a closer look, but I don't promise anything.

**Comment by Stack3r** [comment] 2022-09-12 00:11
Thank you, I also use another streaming .strm file of Toonami Aftermath and it can play for hours without issue, I only encounter this issue with the YouTube plugin

**Comment by antonic901** [comment] 2022-11-07 00:50
Hi. I tried to reproduce this on my Xbox and I noticed one strange thing. While using direct connection to invidious instance I had same problem as you on all videos. Some videos will freeze at 13-14 min, some will freeze at 4 min. But using PC Gateway I hadn't such problem. I've played a music mix of 2 hours without a single freeze on my 128MB Xbox.

Can you try to reproduce this problem using PC Gateway? I'mthinking that maybe there is something wrong with public Invidious instance rather then XBMC/plugin.

**Comment by Stack3r** [comment] 2022-11-17 00:02
At the moment I can't get any videos to load, the search option isn't even working for some reason

**Comment by antonic901** [comment] 2022-11-18 07:16
Hmm, that's strange. What are you using? Public Instance or PC as proxy to public instance?

**Comment by Stack3r** [comment] 2022-12-06 23:35
Public instance I think, I've just been using the app all this time

**Comment by antonic901** [comment] 2022-12-06 23:55
Never mind, I will be releasing a completely rewriten app using xbmcswift2 in next few days. I think I also managed to fix freezing bug. If you want, ping me on email and I will send you current build so you can test it.

**Comment by antonic901** [comment] 2022-12-08 22:51
Fixed as of [v0.5.1](https://github.com/antonic901/xbox-youtube/releases/tag/v0.5.1)

**Closed as completed** 2022-12-08 22:51 UTC
